### ISSUE TITLE
Error in VAT RATE node while passing OutOfScope and VatExemption not accepting by Hungary tax authority

### ISSUE THREAD

**Issue by varshashinde04** [nav-gov-hu/Online-Invoice#595] opened 2020-12-10 06:26 UTC
Hello Team,

we are passing 0 VAT amount invoice to Hungary Tax Authority, because of 0 vat amount we are passing vatoutofscope and vatexemption instead of vat percentage.

But we are getting below error .

**<ns0:validationResultCode>ERROR</ns0:validationResultCode>
<ns0:validationErrorCode>SCHEMA_VIOLATION</ns0:validationErrorCode>
<ns0:message>
XML contains on line: [1] and column: [2,143] error: [cvc-complex-type.2.4.b: 
The content of element 'ns2:lineVatRate' is not complete. One of 
'{"http://schemas.nav.gov.hu/OSA/2.0/data":vatPercentage, "http://schemas.nav.gov.hu/OSA/2.0/data":vatExemption,
"http://schemas.nav.gov.hu/OSA/2.0/data":vatOutOfScope, "http://schemas.nav.gov.hu/OSA/2.0/data":vatDomesticReverseCharge, "http://schemas.nav.gov.hu/OSA/2.0/data":marginSchemeVat, 
"http://schemas.nav.gov.hu/OSA/2.0/data":marginSchemeNoVat}' is expected.]
</ns0:message>**

Thanks in advance

Varsha shinde

**Comment by csandazoltan** [comment] 2020-12-11 06:29
How do you pass it? Do you use a case/reason pair as per the documentation? 
page 123/134 
(WARNING the english documentation is not seems to be up to date to the 2020-12-01 changes)

You can only pass ONE, it is a choice type, it cannot be both!
Both exemption and out of scope has its list of cases

It should look like something like this
<lineVatRate>
   <vatExemption>
     <case>AAM</case>
     <reason>some reason text</reason>
   </vatExemption>
</lineVatRate>

<lineVatRate>
   <vatOutOfScope>
     <case>ATK</case>
     <reason>some reason text</reason>
   </vatOutOfScope>
</lineVatRate>

**Comment by varshashinde04** [comment] 2020-12-11 06:56
Hello ,
thank you for reply.
we are not passing both entries.

for vat out of scope we are passing like this.


-<lineVatRate>

<vatOutOfScope>true</vatOutOfScope>

</lineVatRate>


for vat exemption we are passing in below format.

<lineVatRate>

<vatExemption>Based on Section 169 m) of the VAT Act</vatExemption>

</lineVatRate>

**Comment by csandazoltan** [comment] 2020-12-11 06:58
Put your xml inside "insert code" tags, otherwise the structure is invisible

**Comment by varshashinde04** [comment] 2020-12-11 06:59
yes

**Comment by varshashinde04** [comment] 2020-12-11 06:59
> -<lineVatRate>

<vatExemption>Based on Section 169 m) of the VAT Act</vatExemption>

</lineVatRate>

**Comment by varshashinde04** [comment] 2020-12-11 07:00
`-<lineVatRate>

<vatExemption>Based on Section 169 m) of the VAT Act</vatExemption>

</lineVatRate>`

**Comment by varshashinde04** [comment] 2020-12-11 07:02
I am sorry.
i am not able to copy the XML

**Comment by csandazoltan** [comment] 2020-12-11 07:03
Sure you can, copy it in your comment, select the xml and click on the "insert code" button

It will put markers around it

**Comment by varshashinde04** [comment] 2020-12-11 07:04
yes..thank you so much

**Comment by csandazoltan** [comment] 2020-12-11 07:05
There you go!
Now, that is wrong, i think it was changed around november
They are not boolean or text anymore, you need to use a case/reason pair.

The case is a predefined set of codes, the reason a is a text
Documentation "vatRateType" type

![image](https://user-images.githubusercontent.com/6756505/101873681-ac2a2900-3b87-11eb-8745-4727541129a3.png)

**Comment by varshashinde04** [comment] 2020-12-11 07:07
it will be very helpful if you provide this updated document

**Comment by csandazoltan** [comment] 2020-12-11 07:10
It is on the official site
https://onlineszamla-test.nav.gov.hu/dokumentaciok 
(English language selector on the top right)

BUT BE WARNED! The english translation is not up to date to the latest XSD changes of 2020-12-01
AND the test server does not uses the latest XSD yet!

**Comment by varshashinde04** [comment] 2020-12-11 07:16
Thank you so much

**Comment by varshashinde04** [comment] 2020-12-11 11:49
Hi Zoltan,

if the test server not uses the latest XSD then  why it is thronging error message.
And one more question is this the new SXD version or just a change?

**Comment by csandazoltan** [comment] 2020-12-11 12:30
Short answer: We don't know what is on the test servers, just that it is not the latest

Long answer:
The problem is this, i try to describe it as i understand, bear with me. because we don't really know what is actually on the test server.

Lets define some **arbitrary** versions 
(these have nothing to do with versions of xsd, just for example sake)
Version 1, what you tried to submit
Version 2, what the English documentation is about
Version 3, what is the latest XSD and what is currently downloadable from the site, published on december 8th and hungarian documentation is about

You tried submit Version 1 xml to a server using Version 2.... that is your original error is about

BUT:
As english you cannot start developing because you only have the version 2 documentation, which is obsolete! The latest downloadable XSD is version 3, BUT the server uses Version 2 XSD to verify your xmls
You are stuck at client side verification

As we hungarians also stuck, but on the server side. We have Version 3 documentation, with Version 3 XSD, we can make and verify, hopefully correct requests, BUT the server is gonna throw an error, because it still uses Version 2 to verify your request on the server side!!!

This is messed up!

**Comment by NTCA-supporter** [comment] 2020-12-12 13:20
From now, the test server use the latest 3.0 XSD. If it solve this problem, please close the issue. Thanks

**Comment by NTCA-supporter** [comment] 2021-01-06 14:58
I close the issue due to inactivity.
Br

**Closed by NTCA-supporter** 2021-01-06 14:58 UTC

**Comment by LeeMcMahon** [comment] 2021-02-26 08:57
Hi, I am having a similar issue? do I understand it correctly?

If the invoice you are passing has 0 VAT you only need to send the <VatExemption> tag and not the <VatPercentage> tag also?


so is it this?

`<lineVatRate>
	<vatPercentage>0</vatPercentage>
			    <vatExemption>
			    <case>KBAET</case>
			    <reason>intra-Community exempt supply, without new means of transport</reason>
			</vatExemption>
</lineVatRate>`

or this?

`<lineVatRate>
	<vatExemption>
	    <case>KBAET</case>
	    <reason>intra-Community exempt supply, without new means of transport</reason>
	</vatExemption>
</lineVatRate>`


Thanks

**Comment by NTCA-supporter** [comment] 2021-02-26 09:01
Hi @LeeMcMahon !
The 2nd one is the correct.
lineVatRate contains a choice so you can provide just one type, in this case the vatExemption tag.
Br
